springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation

eureka:  
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    instance:
      hostname: localhost
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSecods: 2

spring:
  cloud:
    discovery:
      enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  liquibase:
    enabled: true    
    change-log: classpath:db/liquibase/master.yml  
  sleuth:
    propagation:
      type: B3,W3C
    opentracing:
      enabled: true
    zipkin:
      base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}

management:
  endpoint:
    health:
      enabled: true
      show-details: always
