server:
  port: 9004
  servlet:
    context-path: /auth

spring:    
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    default-schema: auth

TOKEN:
  PASSWORD: 'senhamegaultrasecreta'
